name: Batch Kolidays

on:
  workflow_dispatch:

jobs:
  batch-kolidays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace SECRET_KEY
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        run: |
          cat batch/src/main/resources/application.conf
          echo '========================='
          sed -i -r "s/^(serviceKey =).*/\1 $SERVICE_KEY/" ./batch/src/main/resources/application.conf
          cat batch/src/main/resources/application.conf
          echo '========================='
          echo 'serviceKey = SERVICE_KEY' >> ./batch/src/main/resources/application.conf
          cat batch/src/main/resources/application.conf
          echo '========================='
