name: Batch Kolidays

on:
  workflow_dispatch:

jobs:
  batch-kolidays:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: git remote -v
        run : git remote -v
